import {useMemo,useRef,useState} from 'react'
import type {WorkspaceContact,WorkspaceLead} from '../crm/types'
import {demoId,type DemoConversation,type DemoModulesState} from './useDemoModules'

type Props={state:DemoModulesState;update:(change:(current:DemoModulesState)=>DemoModulesState)=>void;contacts:WorkspaceContact[];leads:WorkspaceLead[];onOpenLead:(id:string)=>void;onSchedule:(id:string,dueAt:string)=>void;notify:(message:string)=>void}
const initials=(name:string)=>name.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase()

export function DemoInbox({state,update,contacts,leads,onOpenLead,onSchedule,notify}:Props){
  const [selectedId,setSelectedId]=useState(state.conversations[0]?.id??''),[draft,setDraft]=useState(''),[noteMode,setNoteMode]=useState(false),[query,setQuery]=useState(''),[creating,setCreating]=useState(false),[contactId,setContactId]=useState(''),[channel,setChannel]=useState('Website'),[followUp,setFollowUp]=useState(''),[mobileThread,setMobileThread]=useState(false),[notesOpen,setNotesOpen]=useState(false),[noteDraft,setNoteDraft]=useState('')
  const historyRef=useRef<HTMLDivElement>(null)
  const selected=state.conversations.find(item=>item.id===selectedId),contact=contacts.find(item=>item.id===selected?.contactId),lead=leads.find(item=>item.contactId===selected?.contactId||item.name===contact?.name)
  const visible=useMemo(()=>state.conversations.filter(item=>{const person=contacts.find(value=>value.id===item.contactId);return `${person?.name??''} ${item.channel}`.toLowerCase().includes(query.toLowerCase())}),[state.conversations,contacts,query])
  const notes=selected?.messages.filter(message=>message.from==='note')??[]
  const change=(id:string,transform:(item:DemoConversation)=>DemoConversation)=>update(current=>({...current,conversations:current.conversations.map(item=>item.id===id?transform(item):item)}))
  const append=(text:string,from:'note'|'human')=>{if(!selected||!text.trim())return;change(selected.id,item=>({...item,messages:[...item.messages,{id:demoId(),from,text:text.trim(),at:new Date().toISOString()}]}));notify(from==='note'?'Internal note saved':'Demo reply saved in this conversation')}
  const send=()=>{append(draft,noteMode?'note':'human');setDraft('')}
  const addNote=()=>{append(noteDraft,'note');setNoteDraft('')}
  const open=(id:string)=>{setSelectedId(id);setMobileThread(true);setNotesOpen(false);history.pushState({demoInbox:id},'','#app')}
  const create=()=>{if(!contactId)return;const id=demoId();update(current=>({...current,conversations:[{id,contactId,channel,status:'OPEN',humanTakeover:true,messages:[]},...current.conversations]}));setSelectedId(id);setMobileThread(true);setCreating(false);notify('Conversation created')}
  return <>
    <div className="page-heading"><div><p className="eyebrow">Demo conversations</p><h1>Inbox</h1><p className="subheading">Choose a customer, enter the thread, and keep team-only notes beside the conversation.</p></div><button className="btn primary" onClick={()=>{setContactId(contacts[0]?.id??'');setCreating(true)}}>＋ New conversation</button></div>
    <div className={`inbox-layout card live-inbox ${mobileThread?'inbox-thread-open':''}`}>
      <div className="conversation-list"><div className="inbox-list-head"><div><strong>Customer conversations</strong><small>Choose a client to open their thread</small></div><span>{state.conversations.length}</span></div><div className="inbox-search">⌕ <input aria-label="Search inbox" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search people or channels"/></div>{visible.map(item=>{const person=contacts.find(value=>value.id===item.contactId),last=item.messages.at(-1);return <button key={item.id} className={item.id===selectedId?'conversation selected':'conversation'} onClick={()=>open(item.id)}><div className="conversation-avatar">{initials(person?.name??'?')}</div><div><strong>{person?.name??'Unknown contact'}</strong><small>{last?.text??'No messages yet'}</small><em>{item.channel}</em></div><span className="conversation-time">{item.status}</span></button>})}{!visible.length&&<p className="inbox-empty">No conversations match.</p>}</div>
      {selected?<div className="conversation-main"><div className="conversation-head"><button className="inbox-mobile-back" aria-label="Back to conversations" onClick={()=>setMobileThread(false)}>←</button><div className="lead-cell"><div className="lead-avatar">{initials(contact?.name??'?')}</div><div><strong>{contact?.name??'Unknown contact'}</strong><small>{selected.channel} · {selected.status.toLowerCase()}</small></div></div><div className="inbox-head-actions"><button className="inbox-notes-button" onClick={()=>setNotesOpen(true)}>Notes <span>{notes.length}</span></button><select aria-label="Conversation status" value={selected.status} onChange={event=>change(selected.id,item=>({...item,status:event.target.value as DemoConversation['status']}))}><option>OPEN</option><option>CLOSED</option></select></div></div><div className="message-history" ref={historyRef}><div className="date-divider"><span>Conversation history</span></div>{selected.messages.map(message=><div className={`message ${message.from==='note'?'internal-note':message.from}`} key={message.id}><div className="message-label">{message.from==='ai'?'✦ LeadFlow AI':message.from==='human'?'Your team':message.from==='note'?'Internal note':contact?.name??'Customer'}<span>{new Date(message.at).toLocaleString()}</span></div><p>{message.text}</p></div>)}{!selected.messages.length&&<p className="inbox-empty">Write the first message below.</p>}{!selected.humanTakeover&&<div className="takeover-note">✦ AI qualification is active <button onClick={()=>change(selected.id,item=>({...item,humanTakeover:true}))}>Take over conversation</button></div>}</div><div className="composer"><div className="composer-tools"><button aria-pressed={noteMode} onClick={()=>setNoteMode(value=>!value)}>{noteMode?'✓ Internal note':'＋ Internal note'}</button><span>{noteMode?'Only your team can see this note':'Demo reply stays in this browser'}</span></div><div className="composer-input"><textarea value={draft} onChange={event=>setDraft(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();send()}}} placeholder={noteMode?'Write an internal note…':'Write a reply…'}/><button disabled={!draft.trim()} onClick={send}>{noteMode?'Save note':'Send'} ↗</button></div></div></div>:<div className="conversation-main inbox-empty-state">Choose a conversation</div>}
      <aside className="conversation-context"><div className="context-head"><p className="eyebrow">Lead context</p></div>{contact?<><div className="context-profile"><div className="large-avatar">{initials(contact.name)}</div><h2>{contact.name}</h2><span>{contact.company||contact.email}</span></div>{lead&&<><div className="context-section"><small>INTEREST</small><strong>{lead.interest}</strong><span>{lead.stage} · {lead.score} score</span></div><div className="context-section"><small>NEXT ACTION</small><strong>{lead.nextAction}</strong></div><label className="demo-followup">Schedule follow-up<input aria-label="Follow-up date" type="datetime-local" value={followUp} onChange={event=>setFollowUp(event.target.value)}/></label><button className="btn secondary context-button" disabled={!followUp} onClick={()=>{onSchedule(lead.id,new Date(followUp).toISOString());setFollowUp('');notify('Follow-up scheduled')}}>Schedule follow-up</button><button className="btn secondary context-button" onClick={()=>onOpenLead(lead.id)}>Open full profile →</button></>}</>:<p className="inbox-empty">No contact linked.</p>}</aside>
      {notesOpen&&<aside className="client-notes-panel" aria-label="Client notes"><header><div><p className="eyebrow">Team only</p><h2>{contact?.name??'Client'} notes</h2></div><button aria-label="Close client notes" onClick={()=>setNotesOpen(false)}>×</button></header><div className="client-notes-list">{notes.map(note=><article key={note.id}><p>{note.text}</p><time>{new Date(note.at).toLocaleString()}</time></article>)}{!notes.length&&<div className="client-notes-empty"><strong>No notes yet</strong><p>Capture decisions and handoff context only your team should see.</p></div>}</div><form onSubmit={event=>{event.preventDefault();addNote()}}><label htmlFor="demo-client-note">Add a private note</label><textarea id="demo-client-note" value={noteDraft} onChange={event=>setNoteDraft(event.target.value)} placeholder="What should the team remember about this client?"/><button className="btn primary" disabled={!noteDraft.trim()}>Add note</button></form></aside>}
    </div>
    {creating&&<dialog ref={element=>{if(element&&!element.open)element.showModal()}} className="crm-dialog compact" aria-label="New conversation" onCancel={()=>setCreating(false)}><form onSubmit={event=>{event.preventDefault();create()}}><div className="modal-head"><h2>New conversation</h2><button type="button" className="close" onClick={()=>setCreating(false)}>×</button></div><div className="crm-form-grid"><label>Contact<select required value={contactId} onChange={event=>setContactId(event.target.value)}>{contacts.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Channel<select value={channel} onChange={event=>setChannel(event.target.value)}><option>Website</option><option>WhatsApp</option><option>Email</option><option>Referral</option></select></label></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setCreating(false)}>Cancel</button><button className="btn primary" disabled={!contactId}>Create conversation</button></div></form></dialog>}
  </>
}
