import {useCallback,useEffect,useMemo,useState} from 'react'
import {createPortal} from 'react-dom'
import {addOutboundProspects,createOutboundCampaign,loadOutbound,promoteOutboundProspect,saveSequenceStep,updateOutboundCampaign,updateOutboundProspect} from '../../services/outbound'
import type {OutboundCampaignRow,OutboundProspectRow,OutboundSequenceStepRow} from '../../types/database'
import './outbound.css'

const demoCampaign:OutboundCampaignRow={id:'demo-outbound',organization_id:'demo',name:'East Africa growth leaders',website_url:'https://example.com',offer_summary:'Lead qualification and customer follow-up automation',value_proposition:'Respond to every enquiry quickly and keep the team accountable.',target_industries:['Professional services','Hospitality'],target_regions:['Kenya','Uganda'],target_company_sizes:['11–50','51–200'],target_titles:['Founder','Head of Sales'],tone:'PROFESSIONAL',booking_url:null,daily_send_limit:25,status:'READY',created_by:null,created_at:new Date().toISOString(),updated_at:new Date().toISOString()}
const demoProspects:OutboundProspectRow[]=[
  {id:'prospect-1',organization_id:'demo',campaign_id:'demo-outbound',name:'Amina Kamau',email:'amina@example.com',title:'Founder',company:'Example Advisory',website:'https://example.com',country:'Kenya',industry:'Professional services',fit_score:91,research_notes:'Growing advisory team with a visible consultation funnel.',personalized_subject:'A faster follow-up loop for Example Advisory',personalized_body:'Hi Amina, I noticed your team makes it easy to request a consultation. Sevqo LeadFlow can qualify those enquiries and keep every follow-up owned by the right person.',status:'APPROVED',lead_id:null,last_contacted_at:null,replied_at:null,meeting_at:null,created_at:new Date().toISOString(),updated_at:new Date().toISOString()},
  {id:'prospect-2',organization_id:'demo',campaign_id:'demo-outbound',name:'David Otieno',email:'david@example.com',title:'Commercial Director',company:'Lakeview Hospitality',website:null,country:'Kenya',industry:'Hospitality',fit_score:84,research_notes:'Multi-location operator with corporate event enquiries.',personalized_subject:null,personalized_body:null,status:'REVIEW',lead_id:null,last_contacted_at:null,replied_at:null,meeting_at:null,created_at:new Date().toISOString(),updated_at:new Date().toISOString()},
]
const demoSteps:OutboundSequenceStepRow[]=[{id:'step-1',organization_id:'demo',campaign_id:'demo-outbound',position:1,delay_days:0,subject_template:'A practical idea for {{company}}',body_template:'Hi {{first_name}},\n\nI noticed {{research_observation}}. {{value_proposition}}\n\nWorth a short conversation?',created_at:new Date().toISOString(),updated_at:new Date().toISOString()}]
const splitList=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean)
const emptyData={campaigns:[] as OutboundCampaignRow[],prospects:[] as OutboundProspectRow[],steps:[] as OutboundSequenceStepRow[]}
type Tab='Overview'|'Prospects'|'Sequence'|'Settings'

export function OutboundWorkspace({organizationId,isDemo,role,notify}:{organizationId?:string;isDemo:boolean;role:string;notify:(message:string)=>void}){
  const [data,setData]=useState(isDemo?{campaigns:[demoCampaign],prospects:demoProspects,steps:demoSteps}:emptyData)
  const [selectedId,setSelectedId]=useState(isDemo?demoCampaign.id:''),[tab,setTab]=useState<Tab>('Overview'),[dialog,setDialog]=useState<'campaign'|'prospects'|'prospect'|''>('')
  const [selectedProspect,setSelectedProspect]=useState(''),[loading,setLoading]=useState(!isDemo),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const canManage=isDemo||['OWNER','ADMIN','MANAGER'].includes(role)
  const refresh=useCallback(async()=>{if(isDemo||!organizationId)return;setLoading(true);setError('');try{const next=await loadOutbound(organizationId);setData(next);setSelectedId(current=>next.campaigns.some(item=>item.id===current)?current:next.campaigns[0]?.id??'')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load outbound workspace.')}finally{setLoading(false)}},[isDemo,organizationId])
  useEffect(()=>{void refresh()},[refresh])
  const campaign=data.campaigns.find(item=>item.id===selectedId)
  const prospects=data.prospects.filter(item=>item.campaign_id===selectedId)
  const steps=data.steps.filter(item=>item.campaign_id===selectedId)
  const prospect=data.prospects.find(item=>item.id===selectedProspect)
  const metrics=useMemo(()=>({total:prospects.length,approved:prospects.filter(item=>item.status==='APPROVED').length,contacted:prospects.filter(item=>['CONTACTED','REPLIED','INTERESTED','MEETING'].includes(item.status)).length,replies:prospects.filter(item=>['REPLIED','INTERESTED','MEETING'].includes(item.status)).length,meetings:prospects.filter(item=>item.status==='MEETING').length}),[prospects])
  const mutate=async(action:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');try{await action();await refresh();setDialog('');notify(message)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save changes.')}finally{setBusy(false)}}
  const demoSaveCampaign=(input:CampaignInput)=>{const id=`demo-${Date.now()}`;setData(current=>({...current,campaigns:[{...demoCampaign,...input,id,name:input.name,created_at:new Date().toISOString(),updated_at:new Date().toISOString()},...current.campaigns]}));setSelectedId(id);setDialog('');notify('Campaign created in demo mode')}
  const demoImport=(rows:ProspectInput[])=>{if(!campaign)return;setData(current=>({...current,prospects:[...rows.map((row,index)=>({...demoProspects[0],...row,id:`demo-import-${Date.now()}-${index}`,campaign_id:campaign.id,created_at:new Date().toISOString(),updated_at:new Date().toISOString()})),...current.prospects]}));setDialog('');notify('Prospects imported in demo mode')}
  const demoUpdateProspect=(id:string,changes:Partial<OutboundProspectRow>)=>{setData(current=>({...current,prospects:current.prospects.map(item=>item.id===id?{...item,...changes}:item)}));setDialog('');notify('Prospect updated in demo mode')}
  const demoSaveSequence=(position:number,delay_days:number,subject_template:string,body_template:string)=>{if(!campaign)return;const next={...demoSteps[0],id:`demo-step-${position}`,campaign_id:campaign.id,position,delay_days,subject_template,body_template,updated_at:new Date().toISOString()};setData(current=>({...current,steps:[...current.steps.filter(item=>item.campaign_id!==campaign.id||item.position!==position),next]}));notify('Sequence saved in demo mode')}
  const demoSaveSettings=(changes:Partial<OutboundCampaignRow>)=>{if(!campaign)return;setData(current=>({...current,campaigns:current.campaigns.map(item=>item.id===campaign.id?{...item,...changes}:item)}));notify('Campaign updated in demo mode')}
  return <div className="outbound-page"><div className="page-heading"><div><p className="eyebrow">Outbound growth</p><h1>Campaigns</h1><p className="subheading">Define your market, review prospects and messaging, then connect a verified provider when you are ready to send.</p></div>{canManage&&<button className="btn primary" onClick={()=>setDialog('campaign')}>＋ New campaign</button>}</div>
    <div className="outbound-provider-note"><span>↗</span><div><strong>Research and sending provider required</strong><p>The campaign workspace is operational. Automated web research, contact enrichment, address validation, mailbox sending and calendar booking stay disabled until their providers are configured.</p></div></div>
    {error&&<div className="agency-error" role="alert">{error}<button onClick={()=>void refresh()}>Retry</button></div>}
    {loading?<p role="status">Loading campaigns…</p>:<div className="outbound-layout"><aside className="card outbound-campaign-list"><header><strong>Campaigns</strong><span>{data.campaigns.length}</span></header>{data.campaigns.map(item=><button key={item.id} className={selectedId===item.id?'active':''} onClick={()=>{setSelectedId(item.id);setTab('Overview')}}><span>{item.name}</span><small>{item.status.toLowerCase()} · {data.prospects.filter(row=>row.campaign_id===item.id).length} prospects</small></button>)}{!data.campaigns.length&&<p>No campaigns yet. Start with the offer and market you want to reach.</p>}</aside><main className="outbound-main">{campaign?<><div className="card outbound-campaign-head"><div><span className="agency-pill">{campaign.status}</span><h2>{campaign.name}</h2><p>{campaign.value_proposition||'Value proposition not defined yet.'}</p></div>{canManage&&<button className="btn secondary" onClick={()=>setTab('Settings')}>Edit campaign</button>}</div><nav className="outbound-tabs" aria-label="Campaign workspace">{(['Overview','Prospects','Sequence','Settings'] as Tab[]).map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</nav>{tab==='Overview'&&<Overview campaign={campaign} metrics={metrics} prospects={prospects}/>} {tab==='Prospects'&&<ProspectTable prospects={prospects} canManage={canManage} onAdd={()=>setDialog('prospects')} onOpen={id=>{setSelectedProspect(id);setDialog('prospect')}} onStatus={(id,status)=>isDemo?demoUpdateProspect(id,{status}):void mutate(()=>updateOutboundProspect(organizationId!,id,{status}),'Prospect updated')}/>} {tab==='Sequence'&&<SequenceEditor steps={steps} canManage={canManage} saving={busy} onSave={(position,delay_days,subject_template,body_template)=>isDemo?demoSaveSequence(position,delay_days,subject_template,body_template):void mutate(()=>saveSequenceStep(organizationId!,campaign.id,{position,delay_days,subject_template,body_template}),'Sequence saved')}/>} {tab==='Settings'&&<CampaignSettings campaign={campaign} canManage={canManage} saving={busy} onSave={changes=>isDemo?demoSaveSettings(changes):void mutate(()=>updateOutboundCampaign(organizationId!,campaign.id,changes),'Campaign updated')}/>}</>:<div className="card agency-empty">Choose or create a campaign to plan outbound growth.</div>}</main></div>}
    {dialog==='campaign'&&createPortal(<CampaignDialog busy={busy} error={error} onClose={()=>setDialog('')} onSave={input=>isDemo?demoSaveCampaign(input):void mutate(()=>createOutboundCampaign(organizationId!,input),'Campaign created')}/>,document.body)}
    {dialog==='prospects'&&campaign&&createPortal(<ProspectImportDialog busy={busy} error={error} onClose={()=>setDialog('')} onSave={rows=>isDemo?demoImport(rows):void mutate(()=>addOutboundProspects(organizationId!,campaign.id,rows),'Prospects imported')}/>,document.body)}
    {dialog==='prospect'&&prospect&&createPortal(<ProspectDialog prospect={prospect} busy={busy} error={error} onClose={()=>setDialog('')} onSave={changes=>isDemo?demoUpdateProspect(prospect.id,changes):void mutate(()=>updateOutboundProspect(organizationId!,prospect.id,changes),'Prospect saved')} onPromote={()=>isDemo?notify('CRM promotion is available in a live workspace'):void mutate(()=>promoteOutboundProspect(organizationId!,prospect.id),'Prospect added to CRM')}/>,document.body)}
  </div>
}

function Overview({campaign,metrics,prospects}:{campaign:OutboundCampaignRow;metrics:{total:number;approved:number;contacted:number;replies:number;meetings:number};prospects:OutboundProspectRow[]}){const responseRate=metrics.contacted?Math.round(metrics.replies/metrics.contacted*100):0;return <><div className="outbound-metrics">{[['Prospects',metrics.total],['Approved',metrics.approved],['Contacted',metrics.contacted],['Replies',metrics.replies],['Meetings',metrics.meetings],['Reply rate',`${responseRate}%`]].map(([label,value])=><div className="card" key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><div className="outbound-overview-grid"><section className="card outbound-brief"><h3>Offer intelligence</h3><dl><dt>Website</dt><dd>{campaign.website_url||'Not set'}</dd><dt>Offer</dt><dd>{campaign.offer_summary||'Not set'}</dd><dt>Value proposition</dt><dd>{campaign.value_proposition||'Not set'}</dd><dt>Tone</dt><dd>{campaign.tone.toLowerCase()}</dd></dl></section><section className="card outbound-brief"><h3>Ideal customer profile</h3><TagGroup label="Industries" values={campaign.target_industries}/><TagGroup label="Regions" values={campaign.target_regions}/><TagGroup label="Company sizes" values={campaign.target_company_sizes}/><TagGroup label="Decision makers" values={campaign.target_titles}/></section></div><section className="card outbound-learning"><div><p className="eyebrow">Campaign learning</p><h3>Evidence before scale</h3><p>Compare reply and meeting outcomes by industry and country. LeadFlow only recommends scaling after recorded outcomes exist.</p></div>{[...new Set(prospects.map(item=>item.industry).filter(Boolean))].map(industry=>{const group=prospects.filter(item=>item.industry===industry),positive=group.filter(item=>['REPLIED','INTERESTED','MEETING'].includes(item.status)).length;return <div key={industry}><strong>{industry}</strong><span>{positive}/{group.length} positive responses</span></div>})}{!prospects.length&&<span>No outcome evidence yet.</span>}</section></>}
function TagGroup({label,values}:{label:string;values:string[]}){return <div className="outbound-tag-group"><small>{label}</small><div>{values.length?values.map(value=><span key={value}>{value}</span>):<em>Not defined</em>}</div></div>}

function ProspectTable({prospects,canManage,onAdd,onOpen,onStatus}:{prospects:OutboundProspectRow[];canManage:boolean;onAdd:()=>void;onOpen:(id:string)=>void;onStatus:(id:string,status:OutboundProspectRow['status'])=>void}){return <section className="card outbound-table"><header><div><h3>Prospect review</h3><p>Review fit, research and personalization before any contact.</p></div>{canManage&&<button className="btn primary" onClick={onAdd}>＋ Add prospects</button>}</header><div className="table-wrap"><table><thead><tr><th>Prospect</th><th>Company</th><th>Fit</th><th>Status</th><th></th></tr></thead><tbody>{prospects.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small>{item.title||item.email||'No contact detail'}</small></td><td>{item.company}<small>{[item.industry,item.country].filter(Boolean).join(' · ')}</small></td><td><span className={item.fit_score>=80?'outbound-fit high':'outbound-fit'}>{item.fit_score}</span></td><td>{canManage?<select aria-label={`Status for ${item.name}`} value={item.status} onChange={event=>onStatus(item.id,event.target.value as OutboundProspectRow['status'])}>{['SOURCED','REVIEW','APPROVED','CONTACTED','REPLIED','INTERESTED','MEETING','DISQUALIFIED','BOUNCED','OPTED_OUT'].map(status=><option key={status}>{status}</option>)}</select>:item.status}</td><td><button className="text-btn" onClick={()=>onOpen(item.id)}>Review →</button></td></tr>)}</tbody></table></div>{!prospects.length&&<p className="agency-empty">No prospects yet. Import reviewed contacts from CSV or add them manually.</p>}</section>}

function SequenceEditor({steps,canManage,saving,onSave}:{steps:OutboundSequenceStepRow[];canManage:boolean;saving:boolean;onSave:(position:number,delay:number,subject:string,body:string)=>void}){const first=steps.find(item=>item.position===1);const [delay,setDelay]=useState(first?.delay_days??0),[subject,setSubject]=useState(first?.subject_template??''),[body,setBody]=useState(first?.body_template??'');return <section className="card outbound-sequence"><div><p className="eyebrow">Reviewable sequence</p><h3>Step 1 · Introduction</h3><p>Use variables such as {'{{first_name}}'}, {'{{company}}'}, {'{{research_observation}}'} and {'{{value_proposition}}'}.</p></div><label>Delay after approval (days)<input type="number" min="0" max="90" value={delay} disabled={!canManage} onChange={event=>setDelay(Number(event.target.value))}/></label><label>Subject template<input value={subject} disabled={!canManage} onChange={event=>setSubject(event.target.value)}/></label><label>Message template<textarea value={body} disabled={!canManage} onChange={event=>setBody(event.target.value)}/></label>{canManage&&<button className="btn primary" disabled={saving||!subject.trim()||!body.trim()} onClick={()=>onSave(1,delay,subject,body)}>{saving?'Saving…':'Save sequence'}</button>}<div className="outbound-safety"><strong>Safety controls</strong><span>Unsubscribe and suppression states are permanent campaign exclusions.</span><span>Daily limit: reviewed in campaign settings.</span><span>Live sending: provider setup required.</span></div></section>}

function CampaignSettings({campaign,canManage,saving,onSave}:{campaign:OutboundCampaignRow;canManage:boolean;saving:boolean;onSave:(changes:Partial<OutboundCampaignRow>)=>void}){const [offer,setOffer]=useState(campaign.offer_summary),[value,setValue]=useState(campaign.value_proposition),[industries,setIndustries]=useState(campaign.target_industries.join(', ')),[regions,setRegions]=useState(campaign.target_regions.join(', ')),[sizes,setSizes]=useState(campaign.target_company_sizes.join(', ')),[titles,setTitles]=useState(campaign.target_titles.join(', ')),[booking,setBooking]=useState(campaign.booking_url??''),[limit,setLimit]=useState(campaign.daily_send_limit);return <form className="card outbound-settings" onSubmit={event=>{event.preventDefault();onSave({offer_summary:offer,value_proposition:value,target_industries:splitList(industries),target_regions:splitList(regions),target_company_sizes:splitList(sizes),target_titles:splitList(titles),booking_url:booking||null,daily_send_limit:limit,status:campaign.status==='DRAFT'?'READY':campaign.status})}}><h3>Campaign strategy</h3><label>Offer summary<textarea value={offer} disabled={!canManage} onChange={event=>setOffer(event.target.value)}/></label><label>Value proposition<textarea value={value} disabled={!canManage} onChange={event=>setValue(event.target.value)}/></label><div className="outbound-form-grid"><label>Industries<input value={industries} disabled={!canManage} onChange={event=>setIndustries(event.target.value)}/></label><label>Regions<input value={regions} disabled={!canManage} onChange={event=>setRegions(event.target.value)}/></label><label>Company sizes<input value={sizes} disabled={!canManage} onChange={event=>setSizes(event.target.value)}/></label><label>Decision-maker titles<input value={titles} disabled={!canManage} onChange={event=>setTitles(event.target.value)}/></label><label>Booking link<input type="url" value={booking} disabled={!canManage} onChange={event=>setBooking(event.target.value)}/></label><label>Daily send limit<input type="number" min="1" max="500" value={limit} disabled={!canManage} onChange={event=>setLimit(Number(event.target.value))}/></label></div>{canManage&&<button className="btn primary" disabled={saving}>{saving?'Saving…':'Save strategy'}</button>}<button type="button" className="btn secondary" disabled title="Connect an outreach provider before activation">Activate campaign · setup required</button></form>}

type CampaignInput=Pick<OutboundCampaignRow,'name'|'website_url'|'offer_summary'|'value_proposition'|'target_industries'|'target_regions'|'target_company_sizes'|'target_titles'|'tone'|'booking_url'|'daily_send_limit'>
function CampaignDialog({busy,error,onClose,onSave}:{busy:boolean;error:string;onClose:()=>void;onSave:(input:CampaignInput)=>void}){const [name,setName]=useState(''),[website,setWebsite]=useState(''),[offer,setOffer]=useState(''),[value,setValue]=useState(''),[industries,setIndustries]=useState(''),[regions,setRegions]=useState(''),[titles,setTitles]=useState('');return <Modal title="New outbound campaign" onClose={onClose}><form onSubmit={event=>{event.preventDefault();onSave({name,website_url:website||null,offer_summary:offer,value_proposition:value,target_industries:splitList(industries),target_regions:splitList(regions),target_company_sizes:[],target_titles:splitList(titles),tone:'PROFESSIONAL',booking_url:null,daily_send_limit:25})}}><label>Campaign name<input value={name} required minLength={2} onChange={event=>setName(event.target.value)}/></label><label>Business website<input type="url" value={website} onChange={event=>setWebsite(event.target.value)} placeholder="https://example.com"/></label><label>What do you sell?<textarea value={offer} required onChange={event=>setOffer(event.target.value)}/></label><label>Why should this market care?<textarea value={value} required onChange={event=>setValue(event.target.value)}/></label><label>Target industries<input value={industries} onChange={event=>setIndustries(event.target.value)} placeholder="Hospitality, Legal services"/></label><label>Regions<input value={regions} onChange={event=>setRegions(event.target.value)} placeholder="Kenya, East Africa"/></label><label>Decision-maker titles<input value={titles} onChange={event=>setTitles(event.target.value)} placeholder="Founder, Head of Sales"/></label>{error&&<p className="agency-error" role="alert">{error}</p>}<ModalActions busy={busy} onClose={onClose}/></form></Modal>}

type ProspectInput=Pick<OutboundProspectRow,'name'|'email'|'title'|'company'|'website'|'country'|'industry'|'fit_score'|'research_notes'|'personalized_subject'|'personalized_body'>
function parseCsv(value:string):ProspectInput[]{const lines=value.trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const parse=(line:string)=>{const cells:string[]=[];let cell='',quoted=false;for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'&&line[i+1]==='"'&&quoted){cell+='"';i++}else if(char==='"')quoted=!quoted;else if(char===','&&!quoted){cells.push(cell.trim());cell=''}else cell+=char}cells.push(cell.trim());return cells};const headers=parse(lines[0]).map(item=>item.toLowerCase().replaceAll(' ','_'));return lines.slice(1).map(line=>{const row=Object.fromEntries(headers.map((header,index)=>[header,parse(line)[index]??'']));return{name:row.name||row.full_name,email:row.email||null,title:row.title||row.job_title||null,company:row.company||row.company_name,website:row.website||null,country:row.country||null,industry:row.industry||null,fit_score:Math.max(0,Math.min(100,Number(row.fit_score)||0)),research_notes:row.research_notes||null,personalized_subject:row.subject||null,personalized_body:row.message||null}}).filter(item=>item.name&&item.company)}
function ProspectImportDialog({busy,error,onClose,onSave}:{busy:boolean;error:string;onClose:()=>void;onSave:(rows:ProspectInput[])=>void}){const [mode,setMode]=useState<'manual'|'csv'>('manual'),[name,setName]=useState(''),[email,setEmail]=useState(''),[title,setTitle]=useState(''),[company,setCompany]=useState(''),[industry,setIndustry]=useState(''),[country,setCountry]=useState(''),[score,setScore]=useState(0),[csv,setCsv]=useState('');const rows=mode==='csv'?parseCsv(csv):[{name,email:email||null,title:title||null,company,website:null,country:country||null,industry:industry||null,fit_score:score,research_notes:null,personalized_subject:null,personalized_body:null}];return <Modal title="Add prospects" onClose={onClose}><div className="outbound-mode"><button className={mode==='manual'?'active':''} onClick={()=>setMode('manual')}>Manual</button><button className={mode==='csv'?'active':''} onClick={()=>setMode('csv')}>CSV paste</button></div><form onSubmit={event=>{event.preventDefault();onSave(rows)}}>{mode==='manual'?<><label>Full name<input required value={name} onChange={event=>setName(event.target.value)}/></label><label>Work email<input type="email" value={email} onChange={event=>setEmail(event.target.value)}/></label><label>Role / title<input value={title} onChange={event=>setTitle(event.target.value)}/></label><label>Company<input required value={company} onChange={event=>setCompany(event.target.value)}/></label><div className="outbound-form-grid"><label>Industry<input value={industry} onChange={event=>setIndustry(event.target.value)}/></label><label>Country<input value={country} onChange={event=>setCountry(event.target.value)}/></label><label>Fit score<input type="number" min="0" max="100" value={score} onChange={event=>setScore(Number(event.target.value))}/></label></div></>:<><p className="outbound-help">Paste CSV with <strong>name, email, title, company, website, country, industry, fit_score</strong>. Nothing is contacted automatically.</p><label>CSV data<textarea className="outbound-csv" required value={csv} onChange={event=>setCsv(event.target.value)} placeholder={'name,email,title,company,country,industry,fit_score\nJane Doe,jane@example.com,Founder,Example Ltd,Kenya,Technology,90'}/></label><p>{rows.length} valid prospect{rows.length===1?'':'s'} detected</p></>}{error&&<p className="agency-error" role="alert">{error}</p>}<ModalActions busy={busy} onClose={onClose} saveLabel="Import" disabled={!rows.length}/></form></Modal>}

function ProspectDialog({prospect,busy,error,onClose,onSave,onPromote}:{prospect:OutboundProspectRow;busy:boolean;error:string;onClose:()=>void;onSave:(changes:Partial<OutboundProspectRow>)=>void;onPromote:()=>void}){const [score,setScore]=useState(prospect.fit_score),[notes,setNotes]=useState(prospect.research_notes??''),[subject,setSubject]=useState(prospect.personalized_subject??''),[body,setBody]=useState(prospect.personalized_body??'');return <Modal title={`${prospect.name} · ${prospect.company}`} onClose={onClose} wide><form onSubmit={event=>{event.preventDefault();onSave({fit_score:score,research_notes:notes||null,personalized_subject:subject||null,personalized_body:body||null,status:subject&&body&&prospect.status==='SOURCED'?'REVIEW':prospect.status})}}><div className="outbound-prospect-meta"><span>{prospect.title||'Role not set'}</span><span>{prospect.email||'Email not set'}</span><span>{prospect.industry||'Industry not set'}</span><span>{prospect.country||'Country not set'}</span></div><label>Fit score<input type="number" min="0" max="100" value={score} onChange={event=>setScore(Number(event.target.value))}/></label><label>Research evidence<textarea value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Verified facts and why this account fits the ICP"/></label><label>Personalized subject<input value={subject} onChange={event=>setSubject(event.target.value)}/></label><label>Personalized message<textarea value={body} onChange={event=>setBody(event.target.value)}/></label><div className="outbound-ai-required"><strong>AI research and drafting</strong><span>Provider setup required. Manual research and drafts remain available.</span></div>{error&&<p className="agency-error" role="alert">{error}</p>}<div className="outbound-dialog-actions"><button className="btn secondary" type="button" disabled={busy||Boolean(prospect.lead_id)} onClick={onPromote}>{prospect.lead_id?'Already in CRM':'Add to CRM'}</button><ModalActions busy={busy} onClose={onClose}/></div></form></Modal>}

function Modal({title,onClose,wide=false,children}:{title:string;onClose:()=>void;wide?:boolean;children:React.ReactNode}){return <div className="outbound-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className={wide?'card outbound-modal wide':'card outbound-modal'} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="close" aria-label="Close" onClick={onClose}>×</button></header>{children}</section></div>}
function ModalActions({busy,onClose,saveLabel='Save',disabled=false}:{busy:boolean;onClose:()=>void;saveLabel?:string;disabled?:boolean}){return <div className="outbound-modal-actions"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary" disabled={busy||disabled}>{busy?'Saving…':saveLabel}</button></div>}
