import {Fragment,useEffect,useMemo,useState} from 'react'
import {getBillingUsage,getSubscription,openBillingPortal,planLimits,startCheckout} from '../../services/billing'
import type {BillingPlan,BillingUsage} from '../../services/billing'
import type {SubscriptionRow} from '../../types/database'
import './billing.css'

const paymentReady=import.meta.env.VITE_BILLING_PROVIDER_READY==='true'
type Plan={id:BillingPlan;name:string;price:string;tagline:string;bestFor:string;highlights:string[];featured?:boolean}
const plans:Plan[]=[
  {id:'STARTER',name:'Starter',price:'KSh 3,000',tagline:'Capture, organize and follow up without operational sprawl.',bestFor:'Solo operators and compact sales teams',highlights:['Unified inbox, CRM and visual pipeline','Website capture and source attribution','Overview, analytics and core automations','Team chat, tasks and contacts']},
  {id:'GROWTH',name:'Growth',price:'KSh 7,500',tagline:'Coordinate acquisition, delivery and automation in one workspace.',bestFor:'Growing agencies and multi-channel teams',featured:true,highlights:['Everything in Starter','AI assistant, knowledge and approvals','Clients, projects, systems and outbound','Advanced automation and integrations']},
  {id:'PRO',name:'Pro',price:'KSh 15,000',tagline:'Run higher-volume client operations with deeper control.',bestFor:'Established agencies and operations teams',highlights:['Everything in Growth','AI agents and operational run centre','Costs, audit activity and client portal','Higher capacity across every workspace']},
]
const featureGroups=[
  {name:'Lead operations',rows:[['Unified inbox & internal notes','Included','Included','Included'],['CRM, pipeline, tasks & contacts','Included','Included','Included'],['Source attribution & website capture','Included','Included','Included'],['Executive & acquisition analytics','Core','Full','Full']]},
  {name:'Automation & intelligence',rows:[['Workflow automations','Core','Advanced','Advanced'],['AI assistant & knowledge','—','Included','Included'],['Approvals & AI agents','—','Approvals','Full'],['Operations run centre','—','Included','Included']]},
  {name:'Agency delivery',rows:[['Clients, projects & systems','—','Included','Included'],['Outbound campaign operations','—','Included','Included'],['Client portal & cost controls','—','Core','Full'],['Audit activity & governance','Core','Full','Full']]},
] as const
const emptyUsage:BillingUsage={members:0,monthlyLeads:0,activeAutomations:0,knowledgeItems:0}
const demoUsage:BillingUsage={members:2,monthlyLeads:37,activeAutomations:2,knowledgeItems:8}
const usageLabels:{key:keyof BillingUsage;label:string}[]=[{key:'members',label:'Team members'},{key:'monthlyLeads',label:'Leads this month'},{key:'activeAutomations',label:'Active automations'},{key:'knowledgeItems',label:'Knowledge items'}]

export function BillingPage({organizationId,demo,canManage,notify}:{organizationId?:string;demo:boolean;canManage:boolean;notify:(message:string)=>void}){
  const [subscription,setSubscription]=useState<SubscriptionRow|null>(null)
  const [usage,setUsage]=useState<BillingUsage>(demo?demoUsage:emptyUsage)
  const [loading,setLoading]=useState(!demo)
  const [previewPlan,setPreviewPlan]=useState<BillingPlan|null>(null)
  useEffect(()=>{if(demo||!organizationId)return;let active=true;setLoading(true);void Promise.all([getSubscription(organizationId),getBillingUsage(organizationId)]).then(([nextSubscription,nextUsage])=>{if(active){setSubscription(nextSubscription);setUsage(nextUsage)}}).catch(reason=>notify(reason instanceof Error?reason.message:'Unable to load billing')).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[demo,notify,organizationId])
  const selectedPlan=(demo?previewPlan:subscription?.plan) as BillingPlan|undefined
  const selected=useMemo(()=>plans.find(plan=>plan.id===selectedPlan),[selectedPlan])
  const limits=selectedPlan?planLimits[selectedPlan]:null
  const action=async(plan:BillingPlan)=>{if(demo){setPreviewPlan(plan);return}if(!organizationId||!paymentReady)return;try{await startCheckout(organizationId,plan)}catch(reason){notify(reason instanceof Error?reason.message:'Unable to start checkout')}}
  return <div className="billing-workspace"><div className="page-heading billing-heading"><div><p className="eyebrow">Workspace subscription</p><h1>Plans & billing</h1><p className="subheading">Choose the operating capacity your team needs and see exactly which LeadFlow workspaces are included.</p></div>{paymentReady&&subscription?.provider_customer_id&&canManage&&<button className="btn secondary" onClick={async()=>{try{await openBillingPortal(organizationId!)}catch(reason){notify(reason instanceof Error?reason.message:'Unable to open billing portal')}}}>Manage billing →</button>}</div>
    {loading?<div className="card billing-status">Loading subscription and usage…</div>:<div className="card billing-status" role="status" aria-label="Subscription summary"><div><span>Current package</span><strong>{demo?(selected?`${selected.name} preview — ${selected.price}`:'Choose a package to preview'):subscription?.plan??'No active package'}</strong></div><div><span>Subscription status</span><strong>{demo?'NO CHARGE':subscription?.status??'SETUP REQUIRED'}</strong></div><div><span>Next renewal</span><strong>{subscription?.current_period_ends_at?new Date(subscription.current_period_ends_at).toLocaleDateString():'Not scheduled'}</strong></div><div><span>Payment provider</span><strong>{paymentReady?'Configured':'Not connected'}</strong></div></div>}
    {!demo&&!paymentReady&&<div className="integration-notice" role="status"><span>ⓘ</span><div><strong>Payment setup required</strong><p>Plans and usage are ready for review. Checkout is disabled until the business connects and verifies a supported payment provider.</p></div></div>}
    {!canManage&&!demo&&<div className="integration-notice"><span>ⓘ</span><div><strong>Billing is restricted</strong><p>Only workspace owners and administrators can change the subscription.</p></div></div>}
    {limits&&<section className="card billing-usage" aria-labelledby="usage-title"><div className="billing-section-head"><div><p className="eyebrow">Capacity monitor</p><h2 id="usage-title">Current usage</h2></div><span>{selected?.name} limits</span></div><div className="usage-grid">{usageLabels.map(item=>{const value=usage[item.key],limit=limits[item.key],percentage=Math.min(100,Math.round(value/limit*100));return <div className="usage-meter" key={item.key}><div><span>{item.label}</span><strong>{value.toLocaleString()} <small>/ {limit.toLocaleString()}</small></strong></div><div className="usage-track" role="progressbar" aria-label={item.label} aria-valuemin={0} aria-valuemax={limit} aria-valuenow={value}><i style={{width:`${percentage}%`}} /></div><small>{Math.max(0,limit-value).toLocaleString()} remaining</small></div>})}</div></section>}
    <section aria-labelledby="packages-title"><div className="billing-section-head"><div><p className="eyebrow">Package options</p><h2 id="packages-title">Scale the system, not the complexity</h2></div><p>All packages use the same professional workspace. Capacity and advanced operating tools expand with your team.</p></div><div className="billing-plans">{plans.map(plan=><article className={`${subscription?.plan===plan.id||demo&&previewPlan===plan.id?'card billing-plan selected':'card billing-plan'} ${plan.featured?'featured':''}`} key={plan.id}>{plan.featured&&<b className="plan-badge">Most popular</b>}<span>{subscription?.plan===plan.id?'CURRENT PACKAGE':'MONTHLY'}</span><h3>{plan.name}</h3><p className="plan-tagline">{plan.tagline}</p><strong>{plan.price}<small>/ month</small></strong><p className="plan-best">Best for: {plan.bestFor}</p><ul>{plan.highlights.map(feature=><li key={feature}><span>✓</span>{feature}</li>)}</ul><div className="plan-capacity"><span>{planLimits[plan.id].users} members</span><span>{planLimits[plan.id].monthlyLeads.toLocaleString()} leads/mo</span><span>{planLimits[plan.id].automations} automations</span><span>{planLimits[plan.id].knowledgeItems.toLocaleString()} knowledge items</span></div><button className="btn primary" disabled={!demo&&(!canManage||!paymentReady)||subscription?.plan===plan.id&&subscription.status==='ACTIVE'} onClick={()=>void action(plan.id)}>{subscription?.plan===plan.id?'Current package':demo&&previewPlan===plan.id?'Selected preview':demo?'Preview plan':!paymentReady?'Setup required':'Choose package'}</button></article>)}</div></section>
    <section className="card package-matrix" aria-labelledby="comparison-title"><div className="billing-section-head"><div><p className="eyebrow">Capability map</p><h2 id="comparison-title">What each package covers</h2></div><p>No vague bundles—see how the existing LeadFlow product fits into each package.</p></div><div className="matrix-scroll"><table><thead><tr><th>Workspace capability</th>{plans.map(plan=><th key={plan.id}>{plan.name}</th>)}</tr></thead><tbody>{featureGroups.map(group=><Fragment key={group.name}><tr className="matrix-group"><th colSpan={4}>{group.name}</th></tr>{group.rows.map(row=><tr key={row[0]}><td>{row[0]}</td>{row.slice(1).map((value,index)=><td key={`${row[0]}-${index}`} className={value==='—'?'unavailable':''}>{value}</td>)}</tr>)}</Fragment>)}</tbody></table></div></section>
    <div className="billing-provider-note"><strong>Provider-dependent services stay separate.</strong><p>AI models, research, enrichment, email validation, mailbox sending, calendar booking and payment processing require your approved external providers and credentials. The app infrastructure can support them, but a package does not claim those providers are connected.</p></div>
    <p className="data-note">{demo?'Preview mode: no checkout or subscription is created.':paymentReady?'Checkout and payment details are handled by the configured provider.':'Prices shown are package information, not an active checkout. Payment setup is required.'}</p>
  </div>
}
