import {useMemo,useRef,useState} from 'react'
import './help.css'

type Guide={id:string;category:'Get started'|'Daily work'|'Automation & AI'|'Measure & manage';title:string;summary:string;module:string;steps:string[];check:string;limit?:string}
const guides:Guide[]=[
  {id:'launch',category:'Get started',title:'Set up your workspace',summary:'The shortest path from a new account to a usable team workspace.',module:'Settings',steps:['Open Settings and add your business name, industry, country, timezone and a website or phone number.','Add your team in Team so every lead can have an accountable owner.','Add approved answers in Knowledge before enabling AI.','Connect a source in Integrations and submit one test enquiry.','Return to Overview and use Recheck on the launch checklist.'],check:'A test enquiry appears in Leads with the correct source and owner.',limit:'The checklist verifies configuration, not real-world delivery. Verify each external channel with its provider before going live.'},
  {id:'source',category:'Get started',title:'Connect a lead source',summary:'Capture enquiries from your website or a webhook-capable platform.',module:'Integrations',steps:['For your website, open the widget builder, choose branding and add every allowed website origin.','Save the widget and copy the install snippet into your website.','For another platform, create a universal source and copy its one-time key to your platform, Zapier, Make or n8n.','Send a test enquiry and confirm its source and details in Leads.','Revoke and replace a source key immediately if it is exposed.'],check:'The test record is attributed to the intended source.',limit:'A universal source requires the other platform to send data through a webhook/API or a bridge. It is not a native OAuth connector.'},
  {id:'team',category:'Get started',title:'Invite and assign your team',summary:'Give the right people access and make ownership visible.',module:'Team',steps:['Open Team and invite a teammate using their work email.','Choose the least-privileged role that covers their job.','Ask them to accept the invitation and confirm they can see the workspace.','Assign a test lead and task to that teammate.','Review access again when a teammate changes role or leaves.'],check:'The person can sign in and the lead shows the correct owner.',limit:'Email invitations require the production email sender and app origin to be configured.'},
  {id:'knowledge',category:'Automation & AI',title:'Teach the assistant approved answers',summary:'Start with reliable business facts, then test before enabling replies.',module:'Knowledge',steps:['Add your products, services, FAQs and policies as separate knowledge entries.','Write answers your team would be comfortable sending to a customer.','Mark reviewed entries active and keep incomplete material in draft.','Open AI Assistant and test a normal question and one it should escalate.','Set handoff rules and only enable AI after the results are acceptable.'],check:'The assistant uses approved content and does not invent an answer for an unknown question.',limit:'Live AI requires server-side provider credentials; a demo or scripted test is not live delivery.'},
  {id:'inbox',category:'Daily work',title:'Work a customer conversation',summary:'Keep the thread, customer context and human handoff together.',module:'Inbox',steps:['Open Inbox and use the conversation list to choose a customer thread.','Read the full history and the linked lead context before replying.','Use an internal note for information only your team should see.','Take over when a customer requests a person or the assistant lacks a verified answer.','Update the lead owner, next action and follow-up date before leaving the thread.'],check:'The next teammate can understand who replied and what should happen next.',limit:'Replies on external channels only leave LeadFlow after that channel is configured and verified.'},
  {id:'lead',category:'Daily work',title:'Create and qualify a lead',summary:'Turn an enquiry into an owned opportunity with a next action.',module:'Leads',steps:['Select Add lead and enter the contact, interest, source and any useful company details.','Record a realistic deal value or budget and set a next action.','Assign an owner so follow-up does not rely on memory.','Open the lead profile to inspect why its score was calculated.','Add notes and a follow-up task as new information arrives.'],check:'The record has a source, owner, clear stage and next action.',limit:'A lead score is a prioritization aid, not a prediction that the customer will purchase.'},
  {id:'pipeline',category:'Daily work',title:'Move a deal through the pipeline',summary:'Use stages as shared definitions, not just a visual board.',module:'Pipeline',steps:['Open Pipeline and select a lead card to review its context.','Move it only when the exit criterion for its current stage is met.','Add a note or task explaining what changed and who owns the next step.','Use Won only for a confirmed sale and Lost for an opportunity that will not proceed.','Check Automations for stage-change rules if you expect movement or follow-up to happen automatically.'],check:'The new stage and next action agree with the customer history.',limit:'Current reports use each lead’s present stage; they do not reconstruct historical time-in-stage.'},
  {id:'automation',category:'Automation & AI',title:'Build and safely launch a workflow',summary:'Trigger → conditions → ordered actions, with a preflight before activation.',module:'Automations',steps:['Start from a playbook or choose the event that should trigger the workflow.','Add narrow conditions so the rule only enrolls intended leads.','Set action parameters such as target stage, owner and task delay.','Choose a representative lead and run the builder preflight without changing data.','Save and activate, then inspect Run history after a real event. Pause the workflow if the outcome is unexpected.'],check:'A matching test lead passes preflight and a real run appears in history.',limit:'A preflight is not a guarantee that an external provider will deliver. Check channel credentials and failed runs separately.'},
  {id:'analytics',category:'Measure & manage',title:'Read a trustworthy performance report',summary:'Use one date range and consistent filters before drawing conclusions.',module:'Analytics',steps:['Choose the date range, then narrow by source, owner or minimum score.','Compare the current period with the prior period for lead acquisition volume.','Open Acquisition & funnel to see lead volume, qualification rate and currently Won revenue by source.','Inspect missing owners or values before relying on a forecast.','Export the filtered records for a review meeting.'],check:'The report’s filters, denominators and missing-data notices match the question you are answering.',limit:'Forecasts are stage-weighted estimates, not booked revenue. Historical stage movement and close dates are unavailable without event-based reporting.'},
  {id:'billing',category:'Measure & manage',title:'Understand billing and launch status',summary:'Know which actions are available before taking payment or live traffic.',module:'Billing',steps:['Open Billing to review the intended plan and usage limits.','Confirm your organization’s legal terms, prices, taxes and refund policy before publishing paid checkout.','Configure a supported payment provider and verify its sandbox flow.','Verify email, app origin, channel credentials and deployment smoke tests.','Only then invite external customers to use the live service.'],check:'A complete test purchase, notification and cancellation flow works in the intended market.',limit:'Checkout and external delivery are not production-ready just because their settings appear in the interface.'},
]
const categories=['All','Get started','Daily work','Automation & AI','Measure & manage'] as const

export function HelpCenter({onNavigate,isDemo,focus='Overview'}:{onNavigate:(module:string)=>void;isDemo:boolean;focus?:string}){
  const [query,setQuery]=useState(''),[category,setCategory]=useState<(typeof categories)[number]>('All')
  const [selected,setSelected]=useState(()=>guides.find(guide=>guide.module===focus)?.id??'launch')
  const article=useRef<HTMLElement>(null)
  const visible=useMemo(()=>guides.filter(guide=>(category==='All'||guide.category===category)&&`${guide.title} ${guide.summary} ${guide.steps.join(' ')}`.toLowerCase().includes(query.trim().toLowerCase())),[category,query])
  const guide=guides.find(item=>item.id===selected)??guides[0]
  const choose=(id:string)=>{setSelected(id);if(window.innerWidth<900)requestAnimationFrame(()=>article.current?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}))}
  return <div className="help-center"><div className="page-heading"><div><p className="eyebrow">LeadFlow product guide</p><h1>Help centre</h1><p className="subheading">Follow a real workflow from setup to result. Each guide tells you what to do, how to check it worked, and what still needs configuration.</p></div></div>
    <div className="help-intro"><div><span>START HERE</span><strong>Make your first customer journey work end to end.</strong><p>Business details → source → qualified lead → owner → follow-up → measured result.</p></div><button className="btn primary" onClick={()=>choose('launch')}>View setup guide ↗</button></div>
    <div className="help-layout"><aside className="help-library" aria-label="Help topics"><label className="help-search">Search guides<input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Try “automation” or “source”"/></label><div className="help-categories" aria-label="Guide category">{categories.map(value=><button key={value} aria-pressed={category===value} onClick={()=>setCategory(value)}>{value}</button>)}</div><div className="help-topic-list">{visible.map(item=><button key={item.id} aria-current={selected===item.id?'true':undefined} onClick={()=>choose(item.id)}><small>{item.category}</small><strong>{item.title}</strong><span>{item.summary}</span></button>)}{!visible.length&&<p className="help-no-results">No guide matched. Try a different task or category.</p>}</div></aside>
      <article ref={article} className="help-article card" aria-live="polite"><p className="eyebrow">{guide.category} / {guide.module}</p><h2>{guide.title}</h2><p className="help-article-summary">{guide.summary}</p><ol>{guide.steps.map((step,index)=><li key={step}><span>{String(index+1).padStart(2,'0')}</span><p>{step}</p></li>)}</ol><div className="help-success"><strong>How to know it worked</strong><p>{guide.check}</p></div>{guide.limit&&<div className="help-boundary"><strong>Before you rely on it</strong><p>{guide.limit}</p></div>}<button className="btn primary" onClick={()=>onNavigate(guide.module)}>Open {guide.module} ↗</button></article></div>
    {isDemo&&<div className="demo-banner help-note"><div className="spark">i</div><div><strong>Running in demo mode</strong><p>Your demo edits stay in this browser. External channel delivery and a shared team workspace require a live account and configured providers.</p></div></div>}
  </div>
}
