import {useMemo,useState} from 'react'

type Lead={name:string;interest:string;source:string;stage:string;score:number;value:string;owner:string;createdAt?:string;nextAction?:string}
const stages=['New','Qualified','Contacted','Meeting','Negotiation','Won','Lost']
const probabilities:Record<string,number>={New:.1,Qualified:.25,Contacted:.4,Meeting:.55,Negotiation:.75,Won:1,Lost:0}
function valueOf(value:string){const clean=value.replaceAll(',',''),numbers=[...clean.matchAll(/[\d.]+/g)].map(match=>Number(match[0])).filter(Number.isFinite);if(!numbers.length)return 0;const average=numbers.reduce((sum,n)=>sum+n,0)/numbers.length;return /m\b/i.test(clean)?average*1_000_000:/k\b/i.test(clean)?average*1_000:average}
const cash=(value:number)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',notation:value>=1_000_000?'compact':'standard',maximumFractionDigits:1}).format(value)
const percent=(n:number,total:number)=>total?`${(n/total*100).toFixed(1)}%`:'—'
const isOpen=(stage:string)=>!['Won','Lost'].includes(stage)
const hasOwner=(lead:Lead)=>Boolean(lead.owner&&lead.owner!=='Unassigned')
type QualityFilter='all'|'missing_value'|'unassigned'

export function Analytics({leads,isDemo=true}:{leads:Lead[];isDemo?:boolean}){
  const [source,setSource]=useState('All'),[owner,setOwner]=useState('All'),[minimum,setMinimum]=useState(0),[group,setGroup]=useState<'source'|'stage'|'owner'>('source'),[selected,setSelected]=useState<string|null>(null),[sort,setSort]=useState('score'),[period,setPeriod]=useState(()=>leads.some(lead=>lead.createdAt)?90:3650),[report,setReport]=useState<'executive'|'acquisition'|'team'>('executive'),[quality,setQuality]=useState<QualityFilter>('all')
  const cutoff=Date.now()-period*86400000
  const periodLeads=leads.filter(lead=>period===3650||Boolean(lead.createdAt&&Number.isFinite(new Date(lead.createdAt).getTime())&&new Date(lead.createdAt).getTime()>=cutoff))
  const filtered=periodLeads.filter(lead=>(source==='All'||lead.source===source)&&(owner==='All'||lead.owner===owner)&&lead.score>=minimum)
  const comparisonPool=leads.filter(lead=>(source==='All'||lead.source===source)&&(owner==='All'||lead.owner===owner)&&lead.score>=minimum)
  const groups=[...new Set(filtered.map(lead=>lead[group]))].map(name=>({name,count:filtered.filter(lead=>lead[group]===name).length,value:filtered.filter(lead=>lead[group]===name).reduce((sum,lead)=>sum+valueOf(lead.value),0)}))
  const rows=filtered.filter(lead=>(selected===null||lead[group]===selected)&&(quality==='all'||(quality==='missing_value'?!valueOf(lead.value):!hasOwner(lead)))).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='value'?valueOf(b.value)-valueOf(a.value):b.score-a.score)
  const won=filtered.filter(lead=>lead.stage==='Won'),pipeline=filtered.filter(lead=>isOpen(lead.stage)).reduce((sum,lead)=>sum+valueOf(lead.value),0),forecast=filtered.filter(lead=>isOpen(lead.stage)).reduce((sum,lead)=>sum+valueOf(lead.value)*(probabilities[lead.stage]??0),0)
  const sources=useMemo(()=>[...new Set(filtered.map(lead=>lead.source))].map(name=>{const items=filtered.filter(lead=>lead.source===name),wins=items.filter(lead=>lead.stage==='Won');return {name,leads:items.length,qualified:items.filter(lead=>['Qualified','Contacted','Meeting','Negotiation','Won'].includes(lead.stage)).length,wins:wins.length,revenue:wins.reduce((sum,lead)=>sum+valueOf(lead.value),0),average:Math.round(items.reduce((sum,lead)=>sum+lead.score,0)/items.length)}}).sort((a,b)=>b.revenue-a.revenue||b.qualified-a.qualified),[filtered])
  const owners=useMemo(()=>[...new Set(filtered.map(lead=>lead.owner))].map(name=>{const items=filtered.filter(lead=>lead.owner===name);return {name,open:items.filter(lead=>isOpen(lead.stage)).length,wins:items.filter(lead=>lead.stage==='Won').length,pipeline:items.filter(lead=>isOpen(lead.stage)).reduce((sum,lead)=>sum+valueOf(lead.value),0),average:Math.round(items.reduce((sum,lead)=>sum+lead.score,0)/items.length)}}).sort((a,b)=>b.wins-a.wins||b.pipeline-a.pipeline),[filtered])
  const reset=()=>{setSource('All');setOwner('All');setMinimum(0);setSelected(null);setQuality('all');setPeriod(leads.some(lead=>lead.createdAt)?90:3650)}
  const exportCsv=()=>{const quote=(value:string|number)=>`"${String(value).replace(/^(\s*)([=+@-])/,'$1\'$2').replaceAll('"','""')}"`,data=[['Name','Source','Owner','Stage','Score','Budget (as entered)','Estimated value'],...rows.map(lead=>[lead.name,lead.source,lead.owner,lead.stage,lead.score,lead.value,valueOf(lead.value)])],url=URL.createObjectURL(new Blob(['\uFEFF'+data.map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'})),anchor=document.createElement('a');anchor.href=url;anchor.download=isDemo?'leadflow-demo-analytics.csv':'leadflow-analytics.csv';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <div className="analytics-workbench"><div className="page-heading"><div><p className="eyebrow">Revenue intelligence · {isDemo?'Demo workspace':'Live workspace'}</p><h1>Understand your opportunities.</h1><p className="subheading">Use the agency command report to track acquisition quality, team performance and revenue movement.</p></div><button className="btn primary" disabled={!rows.length} onClick={exportCsv}>Export filtered CSV ↓</button></div>
    <div className="report-tabs">{(['executive','acquisition','team'] as const).map(value=><button className={report===value?'active':''} onClick={()=>setReport(value)} key={value}>{value==='executive'?'Executive overview':value==='acquisition'?'Acquisition & funnel':'Team performance'}</button>)}</div>
    <div className="insight-controls card"><label>Period<select aria-label="Analytics date range" value={period} onChange={event=>{setPeriod(Number(event.target.value));setSelected(null)}}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={3650}>All time</option></select></label><label>Source<select value={source} onChange={event=>{setSource(event.target.value);setSelected(null)}}>{['All',...new Set(leads.map(lead=>lead.source))].map(value=><option key={value}>{value}</option>)}</select></label><label>Owner<select value={owner} onChange={event=>{setOwner(event.target.value);setSelected(null)}}>{['All',...new Set(leads.map(lead=>lead.owner))].map(value=><option key={value}>{value}</option>)}</select></label><label>Minimum score: {minimum}<input aria-label="Minimum score" type="range" min="0" max="100" value={minimum} onChange={event=>{setMinimum(Number(event.target.value));setSelected(null)}}/></label><button className="btn secondary" onClick={reset}>Reset filters</button></div>
    <div className="metric-grid analytics-metrics">{[['Open pipeline',cash(pipeline)],['Weighted forecast',cash(forecast)],['Won revenue',cash(won.reduce((sum,lead)=>sum+valueOf(lead.value),0))],['Lead-to-win',percent(won.length,filtered.length)],['Average score',filtered.length?Math.round(filtered.reduce((sum,lead)=>sum+lead.score,0)/filtered.length):'—']].map(([label,value])=><div className="card metric" key={label}><div className="metric-top">{label}</div><strong>{value}</strong></div>)}</div>
    <PeriodPulse leads={comparisonPool} period={period}/>
    {report==='executive'&&<><div className="insights-layout"><section className="card insight-panel"><div className="card-head"><div><h2>Pipeline composition</h2><p>Volume and potential value by {group}.</p></div><select aria-label="Group leads by" value={group} onChange={event=>{setGroup(event.target.value as typeof group);setSelected(null)}}><option value="source">source</option><option value="stage">stage</option><option value="owner">owner</option></select></div><div className="breakdown">{groups.map(item=><button key={item.name} aria-pressed={selected===item.name} onClick={()=>setSelected(selected===item.name?null:item.name)}><span>{item.name}<small>{cash(item.value)}</small></span><strong>{item.count} · {percent(item.count,filtered.length)}</strong><i style={{width:percent(item.count,filtered.length)}}/></button>)}</div></section><section className="card insight-panel"><div className="card-head"><div><h2>Forecast confidence</h2><p>Stage-weighted, not an accounting projection.</p></div></div><div className="health-summary"><strong>{cash(forecast)}</strong><span>weighted pipeline</span><p>{filtered.filter(lead=>!hasOwner(lead)).length} unassigned opportunities.</p><p>{filtered.filter(lead=>!valueOf(lead.value)).length} records without a usable deal value.</p><p>{filtered.filter(lead=>lead.stage==='New').length} leads awaiting qualification.</p></div></section></div><StageFunnel leads={filtered}/></>}
    {report==='acquisition'&&<section className="card insight-panel scorecard"><div className="card-head"><div><h2>Source quality scorecard</h2><p>Compare volume, qualification and attributable wins.</p></div></div><div className="table-wrap"><table className="report-table"><thead><tr><th>Source</th><th>Leads</th><th>Qualified</th><th>Qualification rate</th><th>Wins</th><th>Won revenue</th><th>Avg. score</th></tr></thead><tbody>{sources.map(item=><tr key={item.name}><td><strong>{item.name}</strong></td><td>{item.leads}</td><td>{item.qualified}</td><td>{percent(item.qualified,item.leads)}</td><td>{item.wins}</td><td>{cash(item.revenue)}</td><td>{item.average}</td></tr>)}</tbody></table></div></section>}
    {report==='team'&&<section className="owner-scorecards">{owners.map((item,index)=><article className="card" key={item.name}><span className="owner-rank">#{index+1}</span><h2>{item.name}</h2><strong>{item.wins} won</strong><div><span>{item.open} open opportunities</span><span>{cash(item.pipeline)} portfolio</span><span>{item.average} average score</span></div></article>)}</section>}
    <DataQualityPanel leads={filtered} quality={quality} onChange={setQuality}/>
    <section className="card insight-panel"><div className="card-head"><div><h2>Opportunity details {selected&&`· ${selected}`}</h2><p>{rows.length} matching records · values inferred from entered budgets</p></div><label>Sort <select value={sort} onChange={event=>setSort(event.target.value)}><option value="score">Highest score</option><option value="value">Highest value</option><option value="name">Name A–Z</option></select></label></div><div className="table-wrap"><table className="report-table"><thead><tr>{['Lead','Source','Owner','Stage','Score','Budget','Weighted value'].map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((lead,index)=><tr key={lead.name+index}><td>{lead.name}</td><td>{lead.source}</td><td>{lead.owner}</td><td>{lead.stage}</td><td>{lead.score}</td><td>{lead.value}</td><td>{cash(valueOf(lead.value)*(probabilities[lead.stage]??0))}</td></tr>)}</tbody></table>{!rows.length&&<p className="table-empty">No matching leads.</p>}</div></section><details className="report-method"><summary>How these numbers are calculated</summary><p>Open pipeline sums entered values for leads not marked Won or Lost. Weighted forecast applies a fixed probability to those open values by their current stage. Won revenue sums values for leads currently marked Won. Lead-to-win divides Won leads by all matching leads. Date trends group leads by creation date; “currently won” describes their status now, not the date they closed.</p></details><p className="report-footnote">Forecasts use visible deal values and standard stage probabilities. They are directional management tools, not booked revenue. {isDemo?'This report contains fictional demo data.':'This report uses your live workspace records.'}</p></div>
}
function StageFunnel({leads}:{leads:Lead[]}){const counts=stages.map(stage=>({stage,count:leads.filter(lead=>lead.stage===stage).length,value:leads.filter(lead=>lead.stage===stage).reduce((sum,lead)=>sum+valueOf(lead.value),0)}));return <section className="card stage-funnel"><div className="card-head"><div><h2>Current stage distribution</h2><p>A present-day snapshot, not historical stage conversion or leakage.</p></div></div><div>{counts.map(item=><div key={item.stage}><span>{item.stage}</span><i><b style={{width:percent(item.count,Math.max(...counts.map(value=>value.count),1))}}/></i><strong>{item.count}</strong><small>{cash(item.value)}</small></div>)}</div></section>}

function PeriodPulse({leads,period}:{leads:Lead[];period:number}){
  const now=Date.now(), day=86400000, dated=leads.map(lead=>({lead,time:lead.createdAt?new Date(lead.createdAt).getTime():NaN})).filter(item=>Number.isFinite(item.time)&&item.time<=now)
  const allTime=period===3650, start=allTime?Math.min(...dated.map(item=>item.time),now):now-period*day
  const current=dated.filter(item=>item.time>=start), previous=allTime?[]:dated.filter(item=>item.time>=start-period*day&&item.time<start)
  const bucketCount=period===7?7:period===30?10:12, span=Math.max(now-start,day), buckets=Array.from({length:bucketCount},(_,index)=>{
    const low=start+span*index/bucketCount, high=start+span*(index+1)/bucketCount
    return current.filter(item=>item.time>=low&&(index===bucketCount-1?item.time<=high:item.time<high)).length
  }), peak=Math.max(1,...buckets), delta=current.length-previous.length
  return <section className="card period-pulse"><div className="card-head"><div><h2>Lead acquisition trend</h2><p>Created leads by date · {allTime?'all recorded history':`last ${period} days compared with the previous ${period}`}</p></div><span className="period-pulse-total">{current.length} leads</span></div>
    <div className="period-pulse-body"><div className="period-pulse-comparison"><strong>{allTime?'All time':previous.length?`${delta>=0?'+':''}${delta} vs prior period`:'No prior-period leads'}</strong><span>{allTime?'No previous period available':`${previous.length} leads in previous period`}</span><span>{current.filter(item=>item.lead.stage==='Won').length} of this cohort currently Won</span></div><div className="period-pulse-chart" role="img" aria-label={`${current.length} leads created in the selected period. Bucket counts: ${buckets.join(', ')}`}>
      {buckets.map((count,index)=><div className="period-pulse-column" key={index} title={`Interval ${index+1}: ${count} leads`}><i style={{height:`${Math.max(count?8:2,count/peak*100)}%`}}/><span>{count}</span></div>)}
    </div></div><p className="period-pulse-note">Based on lead creation dates; this is not a chart of closed revenue. Records without a valid creation date are excluded from the trend.</p></section>
}

function DataQualityPanel({leads,quality,onChange}:{leads:Lead[];quality:QualityFilter;onChange:(value:QualityFilter)=>void}){
  const missingValue=leads.filter(lead=>!valueOf(lead.value)).length, unassigned=leads.filter(lead=>!hasOwner(lead)).length
  return <section className="card quality-panel"><div className="card-head"><div><h2>Data quality</h2><p>Find records that make ownership and forecasting less reliable. Select a check to filter the details table.</p></div></div><div className="quality-filters">
    {([['all','All records',leads.length],['missing_value','Missing deal value',missingValue],['unassigned','Unassigned owner',unassigned]] as const).map(([key,label,count])=><button key={key} type="button" aria-pressed={quality===key} onClick={()=>onChange(key)}><span>{label}</span><strong>{count}</strong></button>)}
  </div></section>
}
