import {useMemo,useState} from 'react'
import type {LeadAttribution} from './features/crm/types'

type Lead={name:string;interest:string;source:string;stage:string;score:number;value:string;owner:string;createdAt?:string;nextAction?:string;attribution?:LeadAttribution}
const stages=['New','Qualified','Contacted','Meeting','Negotiation','Won','Lost']
const probabilities:Record<string,number>={New:.1,Qualified:.25,Contacted:.4,Meeting:.55,Negotiation:.75,Won:1,Lost:0}
function valueOf(value:string){const clean=value.replaceAll(',',''),numbers=[...clean.matchAll(/[\d.]+/g)].map(match=>Number(match[0])).filter(Number.isFinite);if(!numbers.length)return 0;const average=numbers.reduce((sum,n)=>sum+n,0)/numbers.length;return /m\b/i.test(clean)?average*1_000_000:/k\b/i.test(clean)?average*1_000:average}
const cash=(value:number)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',notation:value>=1_000_000?'compact':'standard',maximumFractionDigits:1}).format(value)
const percent=(n:number,total:number)=>total?`${(n/total*100).toFixed(1)}%`:'—'
const isOpen=(stage:string)=>!['Won','Lost'].includes(stage)
const hasOwner=(lead:Lead)=>Boolean(lead.owner&&lead.owner!=='Unassigned')
const origin=(lead:Lead,kind:'platform'|'campaign'|'ad'|'form')=>{
  const data=lead.attribution
  if(kind==='platform')return data?.platform||lead.source||'Unknown'
  if(kind==='campaign')return data?.campaignName||data?.campaignId||data?.utmCampaign||'Unattributed'
  if(kind==='ad')return data?.adName||data?.adId||'Unattributed'
  return data?.formName||data?.formId||'Unattributed'
}
const originKey=(lead:Lead,kind:'platform'|'campaign'|'ad'|'form')=>{
  if(kind==='platform')return origin(lead,kind)
  const id=kind==='campaign'?lead.attribution?.campaignId:kind==='ad'?lead.attribution?.adId:lead.attribution?.formId
  return `${origin(lead,'platform')}::${kind}::${id||origin(lead,kind)}`
}
function acquisitionRows(leads:Lead[],kind:'platform'|'campaign'|'ad'|'form'){
  return [...new Set(leads.map(lead=>originKey(lead,kind)))].map(key=>{
    const items=leads.filter(lead=>originKey(lead,kind)===key),wins=items.filter(lead=>lead.stage==='Won'),id=kind==='campaign'?items[0].attribution?.campaignId:kind==='ad'?items[0].attribution?.adId:kind==='form'?items[0].attribution?.formId:undefined
    return {key,name:origin(items[0],kind),id,platform:origin(items[0],'platform'),leads:items.length,qualified:items.filter(lead=>['Qualified','Contacted','Meeting','Negotiation','Won'].includes(lead.stage)).length,wins:wins.length,revenue:wins.reduce((sum,lead)=>sum+valueOf(lead.value),0),pipeline:items.filter(lead=>isOpen(lead.stage)).reduce((sum,lead)=>sum+valueOf(lead.value),0),average:Math.round(items.reduce((sum,lead)=>sum+lead.score,0)/items.length)}
  }).sort((a,b)=>b.leads-a.leads||b.revenue-a.revenue)
}
type QualityFilter='all'|'missing_value'|'unassigned'
type ChartType='bar'|'line'

export function Analytics({leads,isDemo=true}:{leads:Lead[];isDemo?:boolean}){
  const [source,setSource]=useState('All'),[platform,setPlatform]=useState('All'),[campaign,setCampaign]=useState('All'),[ad,setAd]=useState('All'),[owner,setOwner]=useState('All'),[minimum,setMinimum]=useState(0),[group,setGroup]=useState<'source'|'stage'|'owner'>('source'),[selected,setSelected]=useState<string|null>(null),[sort,setSort]=useState('score'),[period,setPeriod]=useState(()=>leads.some(lead=>lead.createdAt)?90:3650),[report,setReport]=useState<'executive'|'acquisition'|'team'>('executive'),[quality,setQuality]=useState<QualityFilter>('all'),[chartType,setChartType]=useState<ChartType>('bar')
  const cutoff=Date.now()-period*86400000
  const periodLeads=leads.filter(lead=>period===3650||Boolean(lead.createdAt&&Number.isFinite(new Date(lead.createdAt).getTime())&&new Date(lead.createdAt).getTime()>=cutoff))
  const matches=(lead:Lead)=>(source==='All'||lead.source===source)&&(platform==='All'||origin(lead,'platform')===platform)&&(campaign==='All'||originKey(lead,'campaign')===campaign)&&(ad==='All'||originKey(lead,'ad')===ad)&&(owner==='All'||lead.owner===owner)&&lead.score>=minimum
  const filtered=periodLeads.filter(matches)
  const comparisonPool=leads.filter(matches)
  const groups=[...new Set(filtered.map(lead=>lead[group]))].map(name=>({name,count:filtered.filter(lead=>lead[group]===name).length,value:filtered.filter(lead=>lead[group]===name).reduce((sum,lead)=>sum+valueOf(lead.value),0)}))
  const rows=filtered.filter(lead=>(selected===null||lead[group]===selected)&&(quality==='all'||(quality==='missing_value'?!valueOf(lead.value):!hasOwner(lead)))).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='value'?valueOf(b.value)-valueOf(a.value):b.score-a.score)
  const won=filtered.filter(lead=>lead.stage==='Won'),pipeline=filtered.filter(lead=>isOpen(lead.stage)).reduce((sum,lead)=>sum+valueOf(lead.value),0),forecast=filtered.filter(lead=>isOpen(lead.stage)).reduce((sum,lead)=>sum+valueOf(lead.value)*(probabilities[lead.stage]??0),0)
  const sources=useMemo(()=>[...new Set(filtered.map(lead=>lead.source))].map(name=>{const items=filtered.filter(lead=>lead.source===name),wins=items.filter(lead=>lead.stage==='Won');return {name,leads:items.length,qualified:items.filter(lead=>['Qualified','Contacted','Meeting','Negotiation','Won'].includes(lead.stage)).length,wins:wins.length,revenue:wins.reduce((sum,lead)=>sum+valueOf(lead.value),0),average:Math.round(items.reduce((sum,lead)=>sum+lead.score,0)/items.length)}}).sort((a,b)=>b.revenue-a.revenue||b.qualified-a.qualified),[filtered])
  const breakdowns=useMemo(()=>({platform:acquisitionRows(filtered,'platform'),campaign:acquisitionRows(filtered,'campaign'),ad:acquisitionRows(filtered,'ad'),form:acquisitionRows(filtered,'form')}),[filtered])
  const owners=useMemo(()=>[...new Set(filtered.map(lead=>lead.owner))].map(name=>{const items=filtered.filter(lead=>lead.owner===name);return {name,open:items.filter(lead=>isOpen(lead.stage)).length,wins:items.filter(lead=>lead.stage==='Won').length,pipeline:items.filter(lead=>isOpen(lead.stage)).reduce((sum,lead)=>sum+valueOf(lead.value),0),average:Math.round(items.reduce((sum,lead)=>sum+lead.score,0)/items.length)}}).sort((a,b)=>b.wins-a.wins||b.pipeline-a.pipeline),[filtered])
  const reset=()=>{setSource('All');setPlatform('All');setCampaign('All');setAd('All');setOwner('All');setMinimum(0);setSelected(null);setQuality('all');setPeriod(leads.some(lead=>lead.createdAt)?90:3650)}
  const exportCsv=()=>{const quote=(value:string|number)=>`"${String(value).replace(/^(\s*)([=+@-])/,'$1\'$2').replaceAll('"','""')}"`,data=[['Name','Source','Platform','Campaign','Campaign ID','Ad set','Ad ID','Ad','Form ID','Form','UTM source','UTM medium','UTM campaign','Owner','Stage','Score','Budget (as entered)','Estimated value'],...rows.map(lead=>[lead.name,lead.source,origin(lead,'platform'),origin(lead,'campaign'),lead.attribution?.campaignId??'',lead.attribution?.adSetName??lead.attribution?.adSetId??'',lead.attribution?.adId??'',origin(lead,'ad'),lead.attribution?.formId??'',origin(lead,'form'),lead.attribution?.utmSource??'',lead.attribution?.utmMedium??'',lead.attribution?.utmCampaign??'',lead.owner,lead.stage,lead.score,lead.value,valueOf(lead.value)])],url=URL.createObjectURL(new Blob(['\uFEFF'+data.map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'})),anchor=document.createElement('a');anchor.href=url;anchor.download=isDemo?'leadflow-demo-analytics.csv':'leadflow-analytics.csv';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <div className="analytics-workbench"><div className="page-heading"><div><p className="eyebrow">Revenue intelligence · {isDemo?'Demo workspace':'Live workspace'}</p><h1>Understand your opportunities.</h1><p className="subheading">Use the agency command report to track acquisition quality, team performance and revenue movement.</p></div><button className="btn primary" disabled={!rows.length} onClick={exportCsv}>Export filtered CSV ↓</button></div>
    <div className="report-tabs" role="tablist" aria-label="Analytics reports">{(['executive','acquisition','team'] as const).map(value=><button role="tab" aria-selected={report===value} aria-label={value==='executive'?'Executive overview':value==='acquisition'?'Acquisition & funnel':'Team performance'} className={report===value?'active':''} onClick={()=>setReport(value)} key={value}>{value==='executive'?'Overview':value==='acquisition'?'Acquisition':'Team'}</button>)}</div>
    <div className="insight-controls card"><label>Period<select aria-label="Analytics date range" value={period} onChange={event=>{setPeriod(Number(event.target.value));setSelected(null)}}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option><option value={3650}>All time</option></select></label><label>Source<select value={source} onChange={event=>{setSource(event.target.value);setSelected(null)}}>{['All',...new Set(leads.map(lead=>lead.source))].map(value=><option key={value}>{value}</option>)}</select></label><label>Platform<select aria-label="Platform" value={platform} onChange={event=>{setPlatform(event.target.value);setSelected(null)}}>{['All',...new Set(leads.map(lead=>origin(lead,'platform')))].map(value=><option key={value}>{value}</option>)}</select></label><label>Campaign<select aria-label="Campaign" value={campaign} onChange={event=>{setCampaign(event.target.value);setSelected(null)}}><option value="All">All</option>{acquisitionRows(leads,'campaign').map(item=><option key={item.key} value={item.key}>{item.name} · {item.platform}{item.id?` · ${item.id}`:''}</option>)}</select></label><label>Ad<select aria-label="Ad" value={ad} onChange={event=>{setAd(event.target.value);setSelected(null)}}><option value="All">All</option>{acquisitionRows(leads,'ad').map(item=><option key={item.key} value={item.key}>{item.name} · {item.platform}{item.id?` · ${item.id}`:''}</option>)}</select></label><label>Owner<select value={owner} onChange={event=>{setOwner(event.target.value);setSelected(null)}}>{['All',...new Set(leads.map(lead=>lead.owner))].map(value=><option key={value}>{value}</option>)}</select></label><label>Minimum score: {minimum}<input aria-label="Minimum score" type="range" min="0" max="100" value={minimum} onChange={event=>{setMinimum(Number(event.target.value));setSelected(null)}}/></label><button className="btn secondary" onClick={reset}>Reset filters</button></div>
    <div className="metric-grid analytics-metrics">{[['Open pipeline',cash(pipeline)],['Weighted forecast',cash(forecast)],['Won revenue',cash(won.reduce((sum,lead)=>sum+valueOf(lead.value),0))],['Lead-to-win',percent(won.length,filtered.length)],['Average score',filtered.length?Math.round(filtered.reduce((sum,lead)=>sum+lead.score,0)/filtered.length):'—']].map(([label,value])=><div className="card metric" key={label}><div className="metric-top">{label}</div><strong>{value}</strong></div>)}</div>
    <PeriodPulse leads={comparisonPool} period={period} chartType={chartType} onChartType={setChartType}/>
    {report==='executive'&&<><div className="insights-layout"><section className="card insight-panel"><div className="card-head"><div><h2>Pipeline composition</h2><p>Volume and potential value by {group}.</p></div><select aria-label="Group leads by" value={group} onChange={event=>{setGroup(event.target.value as typeof group);setSelected(null)}}><option value="source">source</option><option value="stage">stage</option><option value="owner">owner</option></select></div><div className="breakdown">{groups.map(item=><button key={item.name} aria-pressed={selected===item.name} onClick={()=>setSelected(selected===item.name?null:item.name)}><span>{item.name}<small>{cash(item.value)}</small></span><strong>{item.count} · {percent(item.count,filtered.length)}</strong><i style={{width:percent(item.count,filtered.length)}}/></button>)}</div></section><section className="card insight-panel"><div className="card-head"><div><h2>Forecast confidence</h2><p>Stage-weighted, not an accounting projection.</p></div></div><div className="health-summary"><strong>{cash(forecast)}</strong><span>weighted pipeline</span><p>{filtered.filter(lead=>!hasOwner(lead)).length} unassigned opportunities.</p><p>{filtered.filter(lead=>!valueOf(lead.value)).length} records without a usable deal value.</p><p>{filtered.filter(lead=>lead.stage==='New').length} leads awaiting qualification.</p></div></section></div><StageFunnel leads={filtered}/></>}
    {report==='acquisition'&&<><section className="card insight-panel scorecard"><div className="card-head"><div><h2>Source quality scorecard</h2><p>Compare volume, qualification and attributable wins by named source.</p></div></div><div className="table-wrap"><table className="report-table"><thead><tr><th>Source</th><th>Leads</th><th>Qualified</th><th>Qualification rate</th><th>Wins</th><th>Won revenue</th><th>Avg. score</th></tr></thead><tbody>{sources.map(item=><tr key={item.name}><td><strong>{item.name}</strong></td><td>{item.leads}</td><td>{item.qualified}</td><td>{percent(item.qualified,item.leads)}</td><td>{item.wins}</td><td>{cash(item.revenue)}</td><td>{item.average}</td></tr>)}</tbody></table></div></section>{(['platform','campaign','ad','form'] as const).map(kind=><section className="card insight-panel scorecard" key={kind}><div className="card-head"><div><h2>{kind==='platform'?'Platform':kind==='campaign'?'Campaign':kind==='ad'?'Ad':'Lead form'} performance</h2><p>Lead volume, quality, pipeline and wins by {kind}. “Unattributed” means the integration did not send this field.</p></div></div><div className="table-wrap"><table className="report-table"><thead><tr><th>{kind==='ad'?'Ad':kind==='form'?'Form':kind==='campaign'?'Campaign':'Platform'}</th><th>Platform</th><th>ID</th><th>Leads</th><th>Qualified</th><th>Qualification rate</th><th>Open pipeline</th><th>Wins</th><th>Won value</th><th>Avg. score</th></tr></thead><tbody>{breakdowns[kind].map(item=><tr key={item.key}><td><strong>{item.name}</strong></td><td>{item.platform}</td><td>{item.id||'—'}</td><td>{item.leads}</td><td>{item.qualified}</td><td>{percent(item.qualified,item.leads)}</td><td>{cash(item.pipeline)}</td><td>{item.wins}</td><td>{cash(item.revenue)}</td><td>{item.average}</td></tr>)}</tbody></table>{!breakdowns[kind].length&&<p className="table-empty">No leads in this period.</p>}</div></section>)}</>}
    {report==='team'&&<section className="owner-scorecards">{owners.map((item,index)=><article className="card" key={item.name}><span className="owner-rank">#{index+1}</span><h2>{item.name}</h2><strong>{item.wins} won</strong><div><span>{item.open} open opportunities</span><span>{cash(item.pipeline)} portfolio</span><span>{item.average} average score</span></div></article>)}</section>}
    <DataQualityPanel leads={filtered} quality={quality} onChange={setQuality}/>
    <section className="card insight-panel"><div className="card-head"><div><h2>Opportunity details {selected&&`· ${selected}`}</h2><p>{rows.length} matching records · values inferred from entered budgets</p></div><label>Sort <select value={sort} onChange={event=>setSort(event.target.value)}><option value="score">Highest score</option><option value="value">Highest value</option><option value="name">Name A–Z</option></select></label></div><div className="table-wrap"><table className="report-table"><thead><tr>{['Lead','Source','Platform','Campaign','Ad','Form','Owner','Stage','Score','Budget','Weighted value'].map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((lead,index)=><tr key={lead.name+index}><td>{lead.name}</td><td>{lead.source}</td><td>{origin(lead,'platform')}</td><td>{origin(lead,'campaign')}</td><td>{origin(lead,'ad')}</td><td>{origin(lead,'form')}</td><td>{lead.owner}</td><td>{lead.stage}</td><td>{lead.score}</td><td>{lead.value}</td><td>{cash(valueOf(lead.value)*(probabilities[lead.stage]??0))}</td></tr>)}</tbody></table>{!rows.length&&<p className="table-empty">No matching leads.</p>}</div></section><details className="report-method"><summary>How these numbers are calculated</summary><p>Open pipeline sums entered values for leads not marked Won or Lost. Weighted forecast applies a fixed probability to those open values by their current stage. Won revenue sums values for leads currently marked Won. Lead-to-win divides Won leads by all matching leads. Date trends group leads by creation date; “currently won” describes their status now, not the date they closed. Campaign, ad and form reports use the attribution mapped by your inbound connector; missing identifiers cannot be inferred. These are lead and deal-value reports, not ad spend or ROAS.</p></details><p className="report-footnote">Forecasts use visible deal values and standard stage probabilities. They are directional management tools, not booked revenue. {isDemo?'This report contains fictional demo data.':'This report uses your live workspace records.'}</p></div>
}
function StageFunnel({leads}:{leads:Lead[]}){const counts=stages.map(stage=>({stage,count:leads.filter(lead=>lead.stage===stage).length,value:leads.filter(lead=>lead.stage===stage).reduce((sum,lead)=>sum+valueOf(lead.value),0)}));return <section className="card stage-funnel"><div className="card-head"><div><h2>Current stage distribution</h2><p>A present-day snapshot, not historical stage conversion or leakage.</p></div></div><div>{counts.map(item=><div key={item.stage}><span>{item.stage}</span><i><b style={{width:percent(item.count,Math.max(...counts.map(value=>value.count),1))}}/></i><strong>{item.count}</strong><small>{cash(item.value)}</small></div>)}</div></section>}

function PeriodPulse({leads,period,chartType,onChartType}:{leads:Lead[];period:number;chartType:ChartType;onChartType:(value:ChartType)=>void}){
  const [hovered,setHovered]=useState<number|null>(null)
  const now=Date.now(), day=86400000, dated=leads.map(lead=>({lead,time:lead.createdAt?new Date(lead.createdAt).getTime():NaN})).filter(item=>Number.isFinite(item.time)&&item.time<=now)
  const allTime=period===3650, start=allTime?Math.min(...dated.map(item=>item.time),now):now-period*day
  const current=dated.filter(item=>item.time>=start), previous=allTime?[]:dated.filter(item=>item.time>=start-period*day&&item.time<start)
  const bucketCount=period===7?7:period===30?10:12, span=Math.max(now-start,day), buckets=Array.from({length:bucketCount},(_,index)=>{
    const low=start+span*index/bucketCount, high=start+span*(index+1)/bucketCount
    return current.filter(item=>item.time>=low&&(index===bucketCount-1?item.time<=high:item.time<high)).length
  }), peak=Math.max(1,...buckets), delta=current.length-previous.length
  const linePoints=buckets.map((count,index)=>`${buckets.length===1?50:index/(buckets.length-1)*100},${92-count/peak*82}`).join(' ')
  const interval=(index:number)=>{const low=new Date(start+span*index/bucketCount),high=new Date(Math.min(now,start+span*(index+1)/bucketCount));return `${low.toLocaleDateString()} – ${high.toLocaleDateString()}`}
  return <section className="card period-pulse"><div className="card-head"><div><h2>Lead acquisition trend</h2><p>Created leads by date · {allTime?'all recorded history':`last ${period} days compared with the previous ${period}`}</p></div><div className="period-pulse-actions"><span className="period-pulse-total">{current.length} leads</span><div className="chart-type-toggle" aria-label="Analytics chart type">{(['bar','line'] as const).map(value=><button key={value} aria-pressed={chartType===value} onClick={()=>onChartType(value)}>{value==='bar'?'Bar':'Line'}</button>)}</div></div></div>
    <div className="period-pulse-body"><div className="period-pulse-comparison"><strong>{allTime?'All time':previous.length?`${delta>=0?'+':''}${delta} vs prior period`:'No prior-period leads'}</strong><span>{allTime?'No previous period available':`${previous.length} leads in previous period`}</span><span>{current.filter(item=>item.lead.stage==='Won').length} of this cohort currently Won</span></div><div className={`period-pulse-chart ${chartType}`} role="group" aria-label={`${chartType} chart. ${current.length} leads created in the selected period. Bucket counts: ${buckets.join(', ')}`} onMouseLeave={()=>setHovered(null)}>
      {chartType==='bar'?buckets.map((count,index)=><div className={`period-pulse-column ${hovered===index?'selected':''}`} key={index}><i style={{height:`${Math.max(count?8:2,count/peak*100)}%`}}/><span>{count}</span></div>):<><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polyline points={linePoints}/>{buckets.map((count,index)=><circle className={hovered===index?'selected':''} key={index} cx={buckets.length===1?50:index/(buckets.length-1)*100} cy={92-count/peak*82} r={hovered===index?'2.4':'1.5'}/>)}</svg><div className="period-line-labels">{buckets.map((count,index)=><span key={index}>{count}</span>)}</div></>}
      <div className="period-pulse-hit-layer">{buckets.map((count,index)=><button type="button" key={index} aria-label={`Interval ${index+1}, ${interval(index)}: ${count} leads`} onMouseEnter={()=>setHovered(index)} onFocus={()=>setHovered(index)} onBlur={()=>setHovered(null)} onKeyDown={event=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();const buttons=event.currentTarget.parentElement?.querySelectorAll('button');buttons?.[(index+(event.key==='ArrowRight'?1:-1)+bucketCount)%bucketCount]?.focus()}}}/>)}</div>
      {hovered!==null&&<div className="period-pulse-tooltip" style={{left:`${Math.max(10,Math.min(90,(hovered+.5)/bucketCount*100))}%`}} role="status"><strong>{buckets[hovered]} lead{buckets[hovered]===1?'':'s'}</strong><span>{interval(hovered)}</span></div>}
    </div></div><p className="period-pulse-note">Hover or focus an interval to see its exact value. Based on lead creation dates; this is not a chart of closed revenue. Records without a valid creation date are excluded from the trend.</p></section>
}

function DataQualityPanel({leads,quality,onChange}:{leads:Lead[];quality:QualityFilter;onChange:(value:QualityFilter)=>void}){
  const missingValue=leads.filter(lead=>!valueOf(lead.value)).length, unassigned=leads.filter(lead=>!hasOwner(lead)).length
  return <section className="card quality-panel"><div className="card-head"><div><h2>Data quality</h2><p>Find records that make ownership and forecasting less reliable. Select a check to filter the details table.</p></div></div><div className="quality-filters">
    {([['all','All records',leads.length],['missing_value','Missing deal value',missingValue],['unassigned','Unassigned owner',unassigned]] as const).map(([key,label,count])=><button key={key} type="button" aria-pressed={quality===key} onClick={()=>onChange(key)}><span>{label}</span><strong>{count}</strong></button>)}
  </div></section>
}
